### Starting TaskPrologue of job 401159 on tf091 at Fri 17 May 2024 05:02:43 PM CEST
Running on cores 0-1,64-65 with governor ondemand
No GPU known
### Finished TaskPrologue

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
BKG
amplitude
index
sigma
loaded dataset:
/home/wecapstor1/caph/mppi045h/nuisance_summary/PKS_flare/HESS_public/dataset-MSH-simulated-2.154434690031884-hr.fits.gz
Traceback (most recent call last):
  File "4_asimov_scan.py", line 186, in read_in_scan
    with open(f"../{c['folder']}/data/4_scan_{note}_{parname1}_{numpoints}.yml", "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '../BKG_MSH_msh/data/4_scan_2.15h_amplitude_20.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "4_asimov_scan.py", line 201, in <module>
    results = read_in_scan("2.15h")
  File "4_asimov_scan.py", line 189, in read_in_scan
    with open(f"../{c['folder']}/data/4_scan_{note}_{parname1}.yml", "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '../BKG_MSH_msh/data/4_scan_2.15h_amplitude.yml'
BKG
index
sigma
amplitude
loaded dataset:
/home/wecapstor1/caph/mppi045h/nuisance_summary/PKS_flare/HESS_public/dataset-MSH-simulated-2.154434690031884-hr.fits.gz
Traceback (most recent call last):
  File "4_asimov_scan.py", line 186, in read_in_scan
    with open(f"../{c['folder']}/data/4_scan_{note}_{parname1}_{numpoints}.yml", "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '../BKG_MSH_msh/data/4_scan_2.15h_index_20.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "4_asimov_scan.py", line 201, in <module>
    results = read_in_scan("2.15h")
  File "4_asimov_scan.py", line 189, in read_in_scan
    with open(f"../{c['folder']}/data/4_scan_{note}_{parname1}.yml", "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '../BKG_MSH_msh/data/4_scan_2.15h_index.yml'
srun: error: tf091: tasks 0-1: Exited with exit code 1
srun: Terminating StepId=401159.0
=== JOB_STATISTICS ===
=== current date     : Fri 17 May 2024 05:03:01 PM CEST
= Job-ID             : 401159 on tinyfat
= Job-Name           : logfiles/4
= Job-Command        : /home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis/4.slurm
= Initial workdir    : /home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis
= Queue/Partition    : work
= Slurm account      : caph with QOS=normal
= Requested resources:  for 1-00:00:00
= Elapsed runtime    : 00:00:19
= Total RAM usage    : 0.0 GiB of requested  GiB (%)   
= Node list          : tf091
= Subm/Elig/Start/End: 2024-05-17T10:23:16 / 2024-05-17T10:23:16 / 2024-05-17T17:02:41 / 2024-05-17T17:03:00
======================
=== Quota infos ======
    Path              Used     SoftQ    HardQ    Gracetime  Filec    FileQ    FiHaQ    FileGrace    
    /home/hpc           83.5G   104.9G   209.7G        N/A     129K     500K   1,000K        N/A    
    /home/vault         75.6G  1048.6G  2097.2G        N/A     135      200K     400K        N/A    
    /home/saturn       920.7G     0.0K     0.0K        N/A  20,963                           N/A    
======================
